language: C

sudo: true

env:
  global:
    - ac_cv_func_malloc_0_nonnull=yes;
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "KOfJHBqx3I7GsY6OIiqBMN5iFkTpeGlj+WwXF/ZaGmG7bYtIx1641mH43ECoaxGH6I4Tkdf2VBX3xTSVaCeT8OO0K3Zr84MRqmfjfzTo1uGkwiZD3e/pahPVjOTb+IGPForskeooix6KgCJQfW6skh8EEy7EPnZTNXJw2XLujj4="

matrix:
  include:
    - compiler: clang
    - compiler: gcc
    - env: TARGET=win WIN_TOOL=i686-w64-mingw32
    - env: TARGET=win WIN_TOOL=x86_64-w64-mingw32
  exclude:
    - env: COVERITY_SCAN_BRANCH=1 TARGET=win

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then
      sudo apt-get -qq update;
    fi

install:
  - date
  - if [ $TRAVIS_OS_NAME == linux ]; then
      sudo ln -s /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/x86_64-linux-gnu/libgcc_s.so;
      sudo apt-get -qq install xutils-dev gengetopt help2man swig python-dev openjdk-7-jdk openjdk-7-jre-headless golang-go gccgo ruby-dev ccache;
      export PATH=/usr/lib/ccache:${PATH};
      ccache -s;
      if   [ "${WIN_TOOL}" == i686-w64-mingw32 ]; then
        sudo apt-get -qq install mingw-w64 mingw-w64-tools binutils-mingw-w64-i686 gcc-mingw-w64-i686;
      elif [ "${WIN_TOOL}" == x86_64-w64-mingw32 ]; then
        sudo apt-get -qq install mingw-w64 mingw-w64-tools binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64;
      fi
    fi
  - make --version
  - uname -a

cache:
  - ccache

before_script:
  - autoreconf -vis
  - ./configure --enable-openssl-install --enable-python --enable-java --enable-ruby --enable-go GCCGOFLAGS="-static-libgcc" SWIGGOPARAMS=" ";

addons:
  coverity_scan:
    project:
      name: "frankmorgner/openpace"
      description: "Cryptographic library for EAC version 2"
    notification_email: morgner@informatik.hu-berlin.de
    build_command: make
    branch_pattern: coverity_scan

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then
      if [ -z "$TARGET" ]; then
        make check;
      else
        make $TARGET;
      fi
    fi
