language: C
compiler: gcc
before_install: sudo apt-get update
install: sudo apt-get install swig python-dev golang-go gccgo
env:
    - CONF="--enable-openssl-install"
    - CONF="--enable-openssl-install --enable-python"
    - CONF="--enable-openssl-install --enable-go" GCCGOFLAGS="-static-libgcc" SWIGGOPARAMS=" "
script: autoreconf -vsi && ./configure $CONF && make && make check
