language: C
compiler: gcc
before_install: sudo apt-get update
install: sudo apt-get install swig python-dev
env:
    - CONF="--enable-openssl-install"
    - CONF="--enable-openssl-install --enable-python"
script: autoreconf -vsi && ./configure $CONF && make && make check-local
