version: 1.0.0.{build}

platform:
  - x86
  - x64

environment:
  PATH: C:\cygwin\bin;C:\swigwin;C:\cccl;%PATH%
  CYGWIN: nodosfilewarning
  CCCL_OPTIONS: --cccl-muffle /W3 /D_CRT_SECURE_NO_DEPRECATE /DWIN32_LEAN_AND_MEAN --cccl-link DelayImp.lib --cccl-link /DELAYLOAD:libeay32.dll --cccl-link /DELAYLOAD:libeac-0.dll
  CC: cccl
  CXX: cccl
  LD: cccl

  matrix:
    - VSVER: 14
    - VSVER: 12
    - VSVER: 10

matrix:
  allow_failures:
    # currently broken, see https://github.com/appveyor/ci/issues/414
    - VSVER: 14
    # not included in AppVeyor right now
    - platform: x64
      VSVER: 10

install:
  - date /T & time /T
  - ps: >-
      If(!(Test-Path -Path "C:\cccl" )) {
        git clone -q --depth=1 git://github.com/frankmorgner/cccl.git "C:\cccl"
      }
  - ps: >-
      If ($env:Platform -Match "x86") {
        $env:VCVARS_PLATFORM="x86"
        $env:OPENSSL="https://slproweb.com/download/Win32OpenSSL-1_0_2d.exe"
        $env:LANG_PLATFORM=""
        $env:ARTIFACT="${env:APPVEYOR_PROJECT_NAME}-${env:APPVEYOR_BUILD_VERSION}_win32-vs${env:VSVER}"
      } Else {
        $env:VCVARS_PLATFORM="amd64"
        $env:OPENSSL="https://slproweb.com/download/Win64OpenSSL-1_0_2d.exe"
        $env:LANG_PLATFORM="-x64"
        $env:ARTIFACT="${env:APPVEYOR_PROJECT_NAME}-${env:APPVEYOR_BUILD_VERSION}_win64-vs${env:VSVER}"
      }
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - echo "Using Visual Studio %VSVER%.0 at %VSCOMNTOOLS%"
  - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%
  - ps: >-
      If(!(Test-Path -Path "C:\OpenSSL" )) {
        Start-FileDownload $env:OPENSSL -FileName C:\WinOpenSSL.exe
        C:\WinOpenSSL.exe /SILENT /VERYSILENT /SP- /SUPPRESSMSGBOXES /NORESTART /DIR="C:\OpenSSL"
      }
  - ps: >-
      If(!(Test-Path -Path "C:\swigwin" )) {
        Start-FileDownload "https://prdownloads.sourceforge.net/swig/swigwin-2.0.12.zip" -FileName swigwin.zip
        7z x swigwin.zip -oswigwin
        move swigwin\swigwin-* C:\swigwin
      }
  - ps: >-
      If(!(Test-Path -Path "C:\gengetopt" )) {
        git clone -q --depth=1 git://git.savannah.gnu.org/gengetopt.git
        bash -c "exec 0</dev/null && unset CC CXX LD && cd gengetopt && autoreconf -i >> /tmp/ggout 2>&1 && ./configure --prefix=C:/gengetopt >> /tmp/ggout 2>&1 && make install >> /tmp/ggout 2>&1 || cat /tmp/ggout"
      }
  - set PATH=C:\Python27%LANG_PLATFORM%;%PATH%
  - set PYTHON_INCLUDE=C:\Python27%LANG_PLATFORM%\include
  - set PYTHON_LIBD=C:\Python27%LANG_PLATFORM%\libs
  - set PYTHON_LIB=python27.lib
  - set OPENPACE_ROOT=C:\%ARTIFACT%
  - python -V
  - bash -c "which python"
  - bash -c "python -V"
  - bash -c "swig -version"
  - bash -c "which cl.exe"
  - bash -c "cl.exe /? 2>&1 | head -n 2"
  - bash -c "which csc.exe"
  - bash -c "csc.exe /? | head -n 2"
  - bash -c "which cccl"
  - bash -c "cccl --version"
  - make --version
  - uname -a

build_script:
  - bash -c "autoreconf -i"
  - bash -c "touch src/cvc-create.1 src/cvc-print.1"
    # copy/rename the libraries to trick libtool
  - bash -c "cp C:/OpenSSL/bin/libeay32.dll C:/OpenSSL/lib/VC/liblibeay32MT.dll"
  - bash -c "cp C:/OpenSSL/lib/VC/libeay32MT.lib C:/OpenSSL/lib/VC/ink.lib"
  - bash -c "cp C:/Windows/System32/ws2_32.dll C:/Windows/System32/libws2_32.dll"
    # Open dummy file descriptor to fix error on cygwin: Bad file descriptor
  - bash -c "exec 0</dev/null && ./configure GENGETOPT='C:/gengetopt/bin/gengetopt.exe --include-getopt' SWIG='C:/swigwin/swig.exe' CRYPTO_LIBS='-LC:/OpenSSL/lib/VC -llibeay32MT' CRYPTO_CFLAGS='-IC:/OpenSSL/include' --prefix=/ || cat config.log"
  - bash -c "exec 0</dev/null && make || true"
    # The import library is not created by libtool. We need to do it by hand!
  - bash -c "cat cross/libeac-0_without_patched_openssl.def | sed 's, DATA,,' > src/.libs/libeac-0.def"
  - bash -c "cd src/.libs && lib /def:libeac-0.def /out:libeac.lib"
    # now re-compile with the import library
  - bash -c "exec 0</dev/null && make install V=1 DESTDIR=C:/$ARTIFACT"
  - bash -c "cp src/.libs/libeac.lib C:/$ARTIFACT/lib"
  - bash -c "cp -r C:/OpenSSL/* C:/$ARTIFACT"
  - ps: >-
      If ($env:Platform -Match "x86") {
        msbuild bindings\win32\eac.sln /p:Configuration=Debug /p:Platform=Win32
      }
  #- cmd: cd C:\%ARTIFACT%\bin && eactest.exe
  - 7z a %ARTIFACT%.zip C:\%ARTIFACT%
  - appveyor PushArtifact %ARTIFACT%.zip

cache:
  - C:\OpenSSL
  #- C:\cccl
  - C:\swigwin
  - C:\gengetopt

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
